---
title             : "PhD proposal: the role of social identity in Swiss urban commons"
shorttitle        : "PhD proposal"

author: 
  - name          : "Pedrazzini Sabina"
    affiliation   : "1"
    #corresponding : yes    # Define only one corresponding author
    #address       : "University of Bern, Centre for Development and Environment (CDE), Mittelstrasse 43, CH-3012 Bern"
    #email         : "sabina.pedrazzini@unibe.ch"
    #role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
     # - "Conceptualization"
     # - "Writing - Original Draft Preparation"
     # - "Writing - Review & Editing"

affiliation:
  - id            : "1"
    institution   : "Centre for Development and Environment, University of Bern"

bibliography      : CommonPaths.json

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_word
---

Since several years, we are facing many global crises, both on the climate and on the social level. For instance, we recently went through a global pandemic, several natural disaster such as fires and floods, wars with consequent humanitarian emergencies, and an important rising in the cost of living. To address these problems, 17 sustainable development goals (SDGs) were created during the 2012 United Nations Conference on Sustainable Development. The aim was to "produce a set of universal goals that meet the urgent environmental, political and economic challenges facing our world" (United Nations Development Program, n.d.). However, according to the latest Global Sustainable Development Report (2023), ten years after the establishment of these goals, we are still far from achieving them[^1]. At the same time, @Steffen2015 proposed the Planetary Boundaries Framework, based on the biophysical processes regulating the stability of the Earth system. This framework defines nine "planetary boundaries", the most important of which are climate change and biosphere integrity. If not overshot, these boundaries insure a safe operating space for human activities. According to the latest update of the Stockholm Resilience Center (2023), six boundaries are already crossed.

[^1]: More specifically, between the measurements of 2019 and 2023, a regression was observed in goals concerning air pollution, agricultural water use, relative poverty rates, food waste, greenhouse gas emissions, and biodiversity and nitrogen use. There were minimal progress on goals related to malnutrition and gender gap, while gains were observed only in few areas such as extreme poverty reduction and global income convergence.

In order to develop a new model for human well-being, @Raworth2017 combined the United Nations' SDGs with the Planetary Boundaries Framework. In her approach, "well-being depends on enabling every person to lead a life of dignity and opportunity, while safeguarding the integrity of Earth's life-supporting systems" [@Raworth2017, p.1]. Her model (shown in Figure 1) allows to define a safe and just space for humanity. The inner boundary (social foundation) is composed by the social-related SDG; a minimum level is necessary to attain these goals. On the other side, the ecological ceiling is based on the Planetary Boundaries Framework and ideally should not be overshot.

![Figure 1. Doughnut with social foundations as inner boundary and ecological ceiling as outer boundary.\
Source: Raworth (2017)](figure%201.png)

As shown in Figure 1, at a global level, social foundations are not fully met and several planetary boundaries are already overshot. Therefore, a radical change is needed to attain Raworth's definition of well-being. In fact, if we stay on a "business-as-usual pathway", the goals will not be achieved by 2030, or even 2050 (GSDR, 2023). However, the path to attain human well-being within planetary boundaries is not the same for every country. In fact, at the moment, there are no countries that satisfy the basic needs of human well-being while using the resources in a globally sustainable way. On one hand, countries in Global North generally ensure their population's needs, but they also overshoot most of the planetary boundaries. On the other hand, in Global South the planetary boundaries are usually respected, but people's needs are not (fully) met [@ONeill2018].

The actual situation would therefore suggest that the social foundation is attained just when planetary boundaries are exceeded. To inverse this tendency, @ONeill2018 suggested that "provisioning systems must be fundamentally restructured to enable basic needs to be met at a much lower level of resource use" (p. 92).

## The commons[^2] as a solution

[^2]: The term "commons" is both singular and plural [@Bollier2014]. For the difference between the singular forms "common" and "commons", see @Feinberg2021.

Since they can assume various forms, commons have been defined in many ways. In fact, according to @Bollier2014 "they can arise whenever a community decides it wishes to manage a resource in a collective manner, with a special regard for equitable access, use and sustainability" (p. 19). Therefore, commons represent a way for people to self-organized to address shared problems [@Bollier2019]. The variety of definitions could be resumed through three key points. First, the commons' goal is to manage shared resources, goods, or territories [@Ostrom1990; @Meroni2022; @Schmelzer2022]. In general, commons allow to find solutions for the needs of the affected people [@Euler2018; @Euler2019]. Secondly, commons are managed by a self-organized community of users, i.e the commoners [@Ostrom1990]. This community can be seen as a "social network of mutual aid, solidarity, and practices of human exchange that are not reduced to the market form" [@DeAngelis2003, p.1]. Commoners are engaged in creating the commons and in defining rules to successfully manage it, and both these practices and the community can be seen as part of the commons itself [@Meroni2022; @Bollier2014]. Moreover, the organization is usually local, egalitarian, integrative, and fair [@Gidwani2011]. The process through which people come together to find solutions, and to create institutions to govern the commons is called "commoning" [@Euler2018; @Schmelzer2022]. Given the essential role of the community in defining a common, considering the characteristics of the specific group of people who is commoning is crucial to have a full understanding of the commons itself [@Dove2019]. Finally, commons are not organized around the generalized market competition [@Euler2019] and do not involve the classic private and public model [@Ostrom1990].

Commons could be a solution to the current social and ecological issues because, as highlighted by the various definitions, they allow people to directly address their problems in a sustainable way. Moreover, commons represent an alternative to the capitalist system, and they are a possible way to attain degrowth [@Euler2019]. This term indicates a radical change at the political and economic level aimed at drastically reduce resource consumption [@Kallis2018]. The goal is to create a socially and ecologically sustainable society, that is not based on economic growth. In fact, the current capitalistic system is "structurally unsustainable, because it builds on structures of insufficiency --- there is no "enough" to it" [@Euler2019, p. 2].

In fact, in degrowth literature, aspects related to commons are mentioned as potential changes toward a new social and economic organization. For example, in @Fitzpatrick2022, guarantee the decommodified and universal provision of fundamental humans needs, promote shared housing, and prioritize self-sufficient communities are part of the objectives that could allow to attain degrowth. Moreover, a shift toward a more democratic economy is also needed, and to realize it commons, solidarity economy, democratic ownership and institutional support for cooperative are essential [@Schmelzer2022].

Although commons have traditionnally been conceptualized as natural common-pool resources, there are more and more studies about non-traditional forms of commons [@Hess2008]. Among them there are urban commons, that gained popularity during last years [@Feinberg2021]. Urban commons are the local resources in which urban residents have a common stake, such as streets, parks, public spaces, or neighborhood amenities [@Foster2011].

URBAN COMMONS

@Hess2008, p.18 (red) =\> list of papers about housing commons

@Hess2008 new commons = commons that are not the traditional natural common-pool resource, one of her section is "neighborhood commons" and include apartment association and community gardens\
\
"Instead of conceptualizing the city as an aggregation of private property rights, we should instead seek to identify and protect common resources and interests in the city commons through limited access rights and collaborative governance strategies that preserve and draw upon existing social networks to manage common city resources" (Foster, 2006, cited in @Hess2008)

@Federici: benefits of urban gardens

## Challenge in commons

-   challenge in commons: social dilemma =\> temptation to pursue personal interest, but if everybody does so the commons will fail @Foster2011: urban commons are also subjected to the classical free-ride problems of TOC
-   "Commons can even be thought of as the social bonds shared by a community, and can include the need for trust, cooperation and human relationships." (Arvanitakis, 2006, cited in @Hess2008)

define cooperation + literature on cooperation

@Poteete2010a: Research based on field studies, laboratory and field experiments, game theory, and agent-based models has conclusively demonstrated that it is possible for individuals to act collectively to manage shared natural resources on a sustainable basis

@Bollier2014: "Hardin's fictional scenario sets forth a system that has no boundaries around the pasture, no rules for managing it, no punishments for over-use and no distinct community of users. But that is not a commons . It is an open access regime, or a free-for -all. A commons has boundaries, rules, social norms and sanctions against free riders."

## The case of Switzerland

According to @ONeill2018, Switzerland completely follows the Global North tendency. In fact, of the 7 planetary boundaries considered in their study, 6 are exceeded, with "Blue water" being the only exception. At the same time, Switzerland achieved 7 out of the 11 social indicators used, while they did not find information for the remaining four, namely "Life satisfaction", "Healthy life expectancy", "Social support" and "Democratic quality"[^3]. However, according to the OECD Better Life Index, Switzerland performs very well also in these four factors. In this context, commons initiatives could be a way to maintain the high levels of social well-being, while allowing to reduce the ecological impact.

[^3]: The data about Switzerland are not in @ONeill2018, because in the paper the authors included only countries with complete information about the indicators. However, on the website associated to the paper, the page "Country Comparison" allow to find the data for every country analyzed by O'Neill and colleagues.

# State of research

Currently, there are not many studies that investigated cooperation in (urban) commons from a social psychological point of view.

About the study of cooperation in (urban) commons

find studies on commons on a psychological perspective/focus on members?

@Singh2017: "[Hardin's] caricature does not take into account the possibility that the shepherd might grieve the loss of his green valley when it degrades, or that grief might galvanize him into action to avert the tragedy. The affective and communicative relations between the pasture and the shepherd and amongst the shepherds and their power to bring both the commoner and the commons into being remain invisible in this picture"\
"affective and communicative relations between the commons and the commoners can lead to more robust theorizing about the commons, and also possibly help in bringing together divergent ways of thinking about the commons"

=\> focus on more individual, relational aspects (affective), but with a quantitative method + rural common

forest in India

@Nightingale2011: "I take some of these insights into the commons debate to think about the role of subjectivity and emotion in creating durable cooperative agreements. In other words, can we conceptualise a 'non-rational' commons?"

fisheries in ??

@Kopelman2002: review of the factors that influence cooperation in commons dilemmas, here's what they identified on the individual level: gender and social motives (SVO) and power (social status) =\> so not really a focus on identity factors or group dynamic factors

@Gifford1997: study of the cooperation in commons but with mathematical models

@DeCaro2021: "Conventional wisdom (rational choice theory) assumes that individuals are destined to collectively destroy vital ecological systems due to their narrow self-interest. In contrast, Humanistic Rational Choice Theory (HRCT) assumes individuals can cooperatively self-govern, devising effective conservation agreements and governance systems to constrain self-interest for mutual benefit. To test this assumption, we examined the motivational, perceptual, and cooperative outcomes of communication in a resource dilemma experiment"

lab studies

papers when typing "commons" and "psychology"

Edney, J. J., & Harper, C. S. (1978). The commons dilemma: A review of contributions from psychology. *Environmental Management*, *2*, 491-507. =\> how the studies of commons contributed to psychology research about decision-making

Fox, D. R. (1985). Psychology, ideology, utopia, and the commons. *American Psychologist, 40*(1), 48--58. [https://doi.org/10.1037/0003-066X.40.1.48](https://psycnet.apa.org/doi/10.1037/0003-066X.40.1.48) =\> how to find communal solution while maintaining individualism (= need)? Literature review, not really a psychological paper

=\> not really in the sense that I mean

@VanVugt2009 =\> incentives, identity, information and institutions

The Psychology of Social Dilemmas (@VanVugt1998) =\> individual and collective solution to social dilemmas, he talks about SD but to model real-life situation such as water shortage or public transportation

=\> both of VV papers mention social identity but it has not been study in a real common, but just in social dilemma real-life situations

@Feinberg2021 mention the creation of a collective identity as a benefit of urban commons, and this helps resilience of commoners

# Gaps

-   few studies that focused in a psychological way on why do people cooperate in commons =\> most of them studied the commons as a whole, without focusing on the individuals that manage them (see references above)

    -   VV applied social psychology to real-life social dilemmas and showed that identification and social norms are very important motivations when deciding whether to cooperate. However, he did not study this effect in commons as we define them

    -   Singh + Nightindale = non-rational factors such as emotions, ... applied to commons, but not in a quantitative way, and not factor related to social psychology

-   studies about individual factors =\> qualitative, lack of quantitative studies in the field

    -   there are quantitative studies about cooperation in commons, but often they are lab experiments that recreate a commons [e.g @Mosler1993; @Brozyna2018]

-   most of the field study are done in rural commons =\> what about urban commons [@Feinberg2021 did a review about UC, but no field study]

-   SOCIAL IDENTITY IS ALWAYS USED AS A SINGLE CONSTRUCT, BUT IN REAL LIFE PEOPLE HAVE MANY SOCIAL IDENTITIES OVERLAPPING!

-   no researches about how different social groups (women vs men, socio-economic status, ...) contribute differently to a common

# Scope

housing initiatives in Switzerland as real-life commons =\> why? find the parallelism between the two (see document prepared for the kick-off meeting)

=\> elements of the definition = shared resource self-managed by a community of users, who contributes to sustainability

CODHA: Founded in 1994 as a non-profit organization, CODHA brings together people who want a different kind of housing, a different quality of life, a different relationship with the home, based on participation, conviviality, and solidarity. The cooperative carries out its projects by pooling financial resources and through the active participation of residents. Internal management of the buildings by the residents also enables them to define a living environment closer to their aspirations

WOGENO: Bern: The co-operative WOGENO Bern buys, builds and finances houses in order to permanently remove them from speculation. It provides its members with affordable living and working space. Self-managed, secure and communal forms of housing are realized. WOGENO Bern is a non-profit organisation and stands for a responsible approach to its social and natural environment. ZH: more or less the same, see: <https://www.wogeno-zuerich.ch/genossenschaft/genossenschaft-wogeno-zuerich/>

check here: <https://gen-suisse.ch/it/inizio/> =\> housing initiatives but more on the rural zones, but can be useful to define "eco-villages"

# Research questions & methods

## Research question 1

*Impact of the context on personal factors.*

How does commons' organization influence the social identification of their members?\
Is the strength of the identification moderated by other social groups?

IV1 = number of activities organized by the housing initiative (HI)\
=\> HI level, ask to the contact person

IV2 = degree of (possible) implication of members in the HI organization\
=\> HI level, ask to the contact person

IV3 = personal amount of contacts with other residents\
=\> individual level, survey

DV1 = social identification as a member of the housing initiative\
=\> individual level, survey

DV2 = perception of other residents and of conflicts within the HI\
[idea: do they see the others as "residents like me" or do they use opposite social groups to describe them?]

DV3 = social identification in other social groups\
=\> individual level, survey

control group:

-   identification as a resident of their building

-   perception of other residents

-   identification in other social groups

'+ include control variables both at the individual + HI level

### Social identification in HI

3 hypothesis:

H1: the social identification as a member of HI is higher than the control group's identification as resident of their building

H2: the strength of the social identification as a member of HI positively correlates with the number of activities organized by the HI

H3: the strength of the social identification as a member of HI positively correlates with the degree of (possible) implication in the HI organization

H2 & H3: look for results about formation of social identity?

### Perception of other residents

Possible survey:

"In your HI there are different categories of residents: full-rent, free-rent, ... (see based on the HI, and provide an explanaition of each category).

-   In which one are you?

-   Measure of prejudice towards others categories"

Hypothesis:

H4: the amount of prejudice against other categories negatively correlates with the personal level of contacts with other residents (intergroup contact hypothesis, @Allport1954)

### Social identification in other social groups

Manipulation?

"Imagine a competition with other HI" + equivalent for control group =\> high vs low salience of resident identity (salience of social identity =\> TIS + look for other theories)

H5: the identification in other social groups is stronger in the low salience condition than in the high salience condition

H5.1: this difference is stronger for the experimental group than for the control group

## Research question 2

*Impact of personal factors on the context*

How does the identification as a HI member impact the participation to the management activities/community activities? How does it impact the relationship with others members (trust, communication, importance of social norms, ...)?

## Research question 3

*Intervention*

Can social identification as a member of HI be strengthen by a behavioural intervention? Can such as intervention have positive effects for sustainability?

Ideas: competition between HI about which one consumes less?

## Research question 4

*Impact of HI on society*

Do HI members have a different perspective on society than control group? Is social organization in HI different than in "normal" houses (work division, care work, ...)?

=\> see Federici on women and commons: women have a very important part in natural commons (see her examples about African and South American women)

open question: is the same in urban commons nowadays? Do women do most of the work?

OR opposite hypothesis = more egalitarian work division because modern urban commons are more progressive than average society?

## Longitudinal research questions

Does social identification impact survey response?\
HI level: mean of social identification + rate of experimental mortality (=\> responding at the survey as a mean to contribute to HI???)

Does it also impact the duration of stay in HI?\
Individual level: does it predict the probability of participation in the next wave of survey?

How does the identification evolve over the waves?

Each wave: list different social groups (included "resident") from the least to the most important =\> see if there is an evolution of the position

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

How does the "common identity" interact with other social identity such as gender, socio-economic status? =\> literature on intersectionality?

@Feinberg2021: Another source of social tensions, which can also lead to exclusions, is the diverse cultures existing [31] (Bogadi, 2017; Di Feliciantonio, 2017b) and divergent interests or views [28] (D'Souza & Nagendra, 2011; Rao, 2013), potentially causing conflicts (Gilmore, 2017; Huron, 2015).

-   number of common activities = proxy for identity management of the commons? The organization should say how many/how frequent the proposed activity are, and if participation is mandatory

-   measure of "commoners identity" and previous social identity =\> commoners should identify less strongly in previous identity that non commoners? and this difference should be linked to the number of activities that are organized?

    -   same items to measure other social identity + for commoners: "being part of the housing is an important part of my identity", for non-commoners: "being part of the city is an important..." (???)

-   common activity = proposed by the housing community, not at the individual level: the overall activity of the community should predict the identification of the individuals

How does the identification as a commoner impact the participation to the management activities/community activities? How does it impact the relationship with others members (trust, communication, importance of social norms, ...)?

-   opposite than before: activity = individual participation --\> the strength of the identification should predict the level of individual participation

-   measure of social norms about participating in these activities

-   measure of trust on others that will participate in these activities

-   measure of all the other identified factors (?)

=\> find similar questions for the control group!!!

Is it possible to improve the participation to commons activities through an external behavioural intervention?

-   tbd based on the results of previous surveys

LAST RESEARCH QUESTION (maybe?): do commoners and non-commoners have different perspectives on society (inequalities, climate change, trust on others about global issues, ...)? Do this difference evolve over time? =\> contribution of commons to sustainability

=\> few questions to insert in each wave of the survey

Control variables:

-   years of living in the community

-   house level = when was the community created

-   house level = distance from the city center, isolation (can impact the identification), shops (can impact how much members need to go to "normal" shops and therefore isolation)

method = multilevel analysis =\> see the citation Christ et al. (2022) in Matthieu's paper

```{r}
library(DiagrammeR)
library(webshot2)
DiagrammeR::grViz("digraph {
graph [layout = neato, rankdir = LR]
 
node [shape = rectangle, fontsize = 24, fontname = Arial]

rec1 [label = 'societal problem', pos='-8,4!', width = 1, height = 0.5, color = transparent]
rec2 [label = 'SDGs far from being reached
GN: how to maintain social well-being while consuming less?
solutions: degrowth => commons and urban commons
cooperation is essential', pos='0,4!', width = 10, height = 3]

rec3 [label = 'state of research', pos='-8,0!', width = 1, height = 0.5, color = transparent]
rec4 [label = 'insert state of research', pos='0,0!', width = 9.5, height = 3]

rec5 [label = 'gaps', pos='-8,-4!', width = 1, height = 0.5, color = transparent]
rec6 [label = 'x', pos='0,-4!', width = 9, height = 3]

rec7 [label = 'scope', pos='-8,-8!', width = 1, height = 0.5, color = transparent]
rec8 [label = 'x', pos='0,-8!', width = 8.5, height = 3]

rec9 [label = 'overall research question', pos='-8,-12!', width = 1, height = 0.5, color = transparent]
rec10 [label = 'x', pos='0,-12!', width = 8, height = 3]

rec11 [label = 'research question 1', pos='-8,-16!', width = 1, height = 0.5, color = transparent]
rec12 [label = 'insert research question 1', pos='0,-16!', width = 7.5, height = 3]

rec13 [label = 'insert method 1', pos='8,-16!', width = 7.5, height = 3]
rec14 [label = 'insert analysis 1', pos='16,-16!', width = 7.5, height = 3]

rec15 [label = 'research question 2', pos='-8,-20!', width = 1, height = 0.5, color = transparent]
rec16 [label = 'insert research question 2', pos='0,-20!', width = 7.5, height = 3]

rec17 [label = 'insert method 2', pos='8,-20!', width = 7.5, height = 3]
rec18 [label = 'insert analysis 2', pos='16,-20!', width = 7.5, height = 3]

rec19 [label = 'research question 3', pos='-8,-24!', width = 1, height = 0.5, color = transparent]
rec20 [label = 'insert research question 3', pos='0,-24!', width = 7.5, height = 3]

rec21 [label = 'insert method 3', pos='8,-24!', width = 7.5, height = 3]
rec22 [label = 'insert analysis 3', pos='16,-24!', width = 7.5, height = 3]

rec2 -> rec4 -> rec6 -> rec8 -> rec10 -> rec12
rec12 -> rec13 -> rec14
rec16 -> rec17 -> rec18
rec20 -> rec21 -> rec22


}",
height = 2000, width = 1300)
```

\newpage

# References

Independent Group of Scientists appointed by the Secretary-General, Global Sustainable Development Report 2023: *Times of crisis, times of change: Science for accelerating transformations to sustainable development*, (United Nations, New York, 2023)

United Nations Development Program (n.d.). *Sustainable Development Goals: Background on the Goals*. Retrieved November 9, 2023, from <https://www.undp.org/sdg-accelerator/background-goals>

University of Leeds (n.d.). *Country Comparisons*. A Good Life For All Within Planetary Boundaries. Retrieved November 9, 2023, from <https://goodlife.leeds.ac.uk/national-snapshots/countries/#Switzerland>

OECD (n.d.). *Switzerland*. OECD Better Life Index. Retrieved November 9, 2023, from <https://www.oecdbetterlifeindex.org/countries/switzerland/>

Stockholm Resilience Centre, Stockholm University (n.d.). *Planetary boundaries*. Retrieved November 20, 2023, from <https://www.stockholmresilience.org/research/planetary-boundaries.html>

Swiss Confederation (2023, June 30). *Population - facts and figures*. About Switzerland. Retrieved November 20, 2023, from <https://www.eda.admin.ch/aboutswitzerland/en/home/gesellschaft/bevoelkerung/die-bevoelkerung---fakten-und-zahlen.html>

::: {#refs custom-style="Bibliography"}
:::
